//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DynamicForms.Areas.SGI.Model
{

    public class T_Configuracoes
    {
        public int CON_ID { get; set; }
    }

    class T_Configuracoes_ResultConfiguration : IEntityTypeConfiguration<T_Configuracoes>
    {
        /*
        * Migração do EntityFramework para o EntityCore, o construtor foi substituido pelo método
        * public void Configure(EntityTypeBuilder<> builder), que é a implementação da interface
        * IEntityTypeConfiguration<>
        * 
        public T_Configuracoes_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.CON_ID);

            this.Property(c => c.CON_ID)
                .HasColumnName("CON_ID")
                .IsRequired();

            // Configurando a Tabela
            this.ToTable("T_CONFIGURACOES");
        }
        */

        public void Configure(EntityTypeBuilder<T_Configuracoes> builder)
        {
            // Configurando propriedades e chaves
            builder.HasKey(c => c.CON_ID);

            builder.Property(c => c.CON_ID)
                .HasColumnName("CON_ID")
                .IsRequired();

            // Configurando a Tabela
            builder.ToTable("T_CONFIGURACOES");
        }
    }
}
