//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DynamicForms.Areas.SGI.Model
{
    public class T_Grupo_Indicador
    {
        public int GRU_IND_ID { get; set; }
        public int GRU_ID { get; set; }
        public int IND_ID { get; set; }
    
        public virtual T_Grupo T_Grupo { get; set; }
        public virtual T_Indicadores T_Indicadores { get; set; }
    }

    class T_Grupo_Indicador_ResultConfiguration : IEntityTypeConfiguration<T_Grupo_Indicador>
    {
        /*
        * Migração do EntityFramework para o EntityCore, o construtor foi substituido pelo método
        * public void Configure(EntityTypeBuilder<> builder), que é a implementação da interface
        * IEntityTypeConfiguration<>
        * 
        public T_Grupo_Indicador_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.GRU_IND_ID);

            this.Property(c => c.GRU_IND_ID)
                .HasColumnName("GRU_IND_ID")
                .IsRequired();

            this.Property(c => c.GRU_ID)
                .HasColumnName("GRU_ID")
                .IsRequired();

            this.HasRequired(c => c.T_Grupo)
                .WithMany(c => c.T_Grupo_Indicador)
                .HasForeignKey(x => x.GRU_ID);

            this.Property(c => c.IND_ID)
                .HasColumnName("IND_ID")
                .IsRequired();

            this.HasRequired(c => c.T_Indicadores)
                .WithMany(c => c.T_Grupo_Indicador)
                .HasForeignKey(x => x.IND_ID);

            // Configurando a Tabela
            this.ToTable("T_GRUPO_INDICADOR");
        }
        */

        public void Configure(EntityTypeBuilder<T_Grupo_Indicador> builder)
        {
            // Configurando propriedades e chaves
            builder.HasKey(c => c.GRU_IND_ID);

            builder.Property(c => c.GRU_IND_ID)
                .HasColumnName("GRU_IND_ID")
                .IsRequired();

            builder.Property(c => c.GRU_ID)
                .HasColumnName("GRU_ID")
                .IsRequired();

            builder.HasOne(c => c.T_Grupo)
                .WithMany(c => c.T_Grupo_Indicador)
                .HasForeignKey(x => x.GRU_ID);

            builder.Property(c => c.IND_ID)
                .HasColumnName("IND_ID")
                .IsRequired();

            builder.HasOne(c => c.T_Indicadores)
                .WithMany(c => c.T_Grupo_Indicador)
                .HasForeignKey(x => x.IND_ID);

            // Configurando a Tabela
            builder.ToTable("T_GRUPO_INDICADOR");
        }
    }
}
