//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicForms.Areas.SGI.Model
{
    using DynamicForms.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class T_Grupo
    {
        public T_Grupo()
        {
            this.T_Grupo_Indicador = new HashSet<T_Grupo_Indicador>();
            this.T_USER_GRUPO = new HashSet<T_USER_GRUPO>();
        }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "ID")] [Required(ErrorMessage = "Campo GRU_ID requirido.")] public int GRU_ID { get; set; }
        [Required(ErrorMessage ="Campo NOME requerido.")]
        [MaxLength(80, ErrorMessage = "Permitido no máximo 80 caracteres.")]
        [TAB(Value = "PRINCIPAL")] public string NOME { get; set; }
        [Required(ErrorMessage = "Campo EXIBELISTA requerido.")]
        public int EXIBELISTA { get; set; }
        [Required(ErrorMessage = "Campo GRU_DESCRICAO requerido.")]
        [MaxLength(2000, ErrorMessage = "Permitido no máximo 2000 caracteres.")]
        public string GRU_DESCRICAO { get; set; }

        public virtual ICollection<T_Grupo_Indicador> T_Grupo_Indicador { get; set; }
        public virtual ICollection<T_USER_GRUPO> T_USER_GRUPO { get; set; }
    }
}
