//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DynamicForms.Areas.SGI.Model
{

    public class T_Tabela
    {
        public int ID_TABELA { get; set; }
        public string CODIGO { get; set; }
        public string NOME { get; set; }
    }

    class T_Tabela_ResultConfiguration : IEntityTypeConfiguration<T_Tabela>
    {
        /*
        * Migração do EntityFramework para o EntityCore, o construtor foi substituido pelo método
        * public void Configure(EntityTypeBuilder<> builder), que é a implementação da interface
        * IEntityTypeConfiguration<>
        * 
        public T_Tabela_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.ID_TABELA);

            this.Property(c => c.ID_TABELA)
                .HasColumnName("ID_TABELA")
                .IsRequired();

            this.Property(c => c.CODIGO)
                .HasColumnName("CODIGO")
                .HasMaxLength(15)
                .IsRequired();

            this.Property(c => c.NOME)
              .HasColumnName("NOME")
              .HasMaxLength(80)
              .IsRequired();

            // Configurando a Tabela
            this.ToTable("T_TABELA");
        }
        */

        public void Configure(EntityTypeBuilder<T_Tabela> builder)
        {
            // Configurando propriedades e chaves
            builder.HasKey(c => c.ID_TABELA);

            builder.Property(c => c.ID_TABELA)
                .HasColumnName("ID_TABELA")
                .IsRequired();

            builder.Property(c => c.CODIGO)
                .HasColumnName("CODIGO")
                .HasMaxLength(15)
                .IsRequired();

            builder.Property(c => c.NOME)
              .HasColumnName("NOME")
              .HasMaxLength(80)
              .IsRequired();

            // Configurando a Tabela
            builder.ToTable("T_TABELA");
        }
    }
}
