//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicForms.Areas.SGI.Model
{
    using DynamicForms.Models;
    using DynamicForms.Util;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class T_Unidade
    {
        public T_Unidade()
        {
            this.T_Medicoes = new HashSet<T_Medicoes>();
            this.T_UNIUSER = new HashSet<T_UNIUSER>();
        }

        [TAB(Value = "PRINCIPAL")] [Display(Name = "ID")] [Required(ErrorMessage = "Campo UNI_ID requirido.")] public int UNI_ID { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "CRICAO")] [Required(ErrorMessage = "Campo DEESCRICAO requirido.")] [MaxLength(100, ErrorMessage = "Maximode 100 caracteres, campo DEESCRICAO")] public string DEESCRICAO { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "")] [Required(ErrorMessage = "Campo UN requirido.")] [MaxLength(20, ErrorMessage = "Maximode 20 caracteres, campo UN")] public string UN { get; set; }
        public virtual ICollection<T_Medicoes> T_Medicoes { get; set; }
        public virtual ICollection<T_UNIUSER> T_UNIUSER { get; set; }
        [NotMapped] public string PlayAction { get; set; }
        [NotMapped] public string PlayMsgErroValidacao { get; set; }
        [NotMapped] public int? IndexClone { get; set; }
        // public bool BeforeChanges(List<object> objects, ref CloneObjeto cloneObjeto, List<LogPlay> Logs, ref int modo_insert) { return true; }
        
    }

    class T_Unidade_ResultConfiguration : IEntityTypeConfiguration<T_Unidade>
    {
        /*
        * Migração do EntityFramework para o EntityCore, o construtor foi substituido pelo método
        * public void Configure(EntityTypeBuilder<> builder), que é a implementação da interface
        * IEntityTypeConfiguration<>
        * 
        public T_Unidade_ResultConfiguration()
        {
            // Configurando propriedades e chaves
            this.HasKey(c => c.UNI_ID);

            this.Property(c => c.UNI_ID)
                .HasColumnName("UNI_ID")
                .IsRequired();

            this.Property(c => c.DESCRICAO)
                .HasColumnName("DEESCRICAO")
                .HasMaxLength(100)
                .IsRequired();

            this.Property(c => c.UN)
              .HasColumnName("UN")
              .HasMaxLength(20)
              .IsRequired();

            // Configurando a Tabela
            this.ToTable("T_Unidade");
        }
        */

        public void Configure(EntityTypeBuilder<T_Unidade> builder)
        {
            // Configurando propriedades e chaves
            builder.HasKey(c => c.UNI_ID);

            builder.Property(c => c.UNI_ID)
                .HasColumnName("UNI_ID")
                .IsRequired();

            builder.Property(c => c.DEESCRICAO)
                .HasColumnName("DEESCRICAO")
                .HasMaxLength(100)
                .IsRequired();

            builder.Property(c => c.UN)
              .HasColumnName("UN")
              .HasMaxLength(20)
              .IsRequired();

            // Configurando a Tabela
            builder.ToTable("T_Unidade");
        }
    }
}
