//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DynamicForms.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DynamicForms.Areas.SGI.Model
{

    public class T_USER_GRUPO
    {
        //public int GRPUSER_ID { get; set; }
        public int GRU_ID { get; set; }
        public int ID_USUARIO { get; set; }
    
        public virtual T_Grupo T_Grupo { get; set; }
        public virtual T_Usuario T_Usuario { get; set; }
    }

    //class T_USER_GRUPO_ResultConfiguration : IEntityTypeConfiguration<T_USER_GRUPO>
    //{
    //    /*
    //    * Migração do EntityFramework para o EntityCore, o construtor foi substituido pelo método
    //    * public void Configure(EntityTypeBuilder<> builder), que é a implementação da interface
    //    * IEntityTypeConfiguration<>
    //    * 
    //    public T_USER_GRUPO_ResultConfiguration()
    //    {
    //        // Configurando propriedades e chaves
    //        this.HasKey(c => c.GRPUSER_ID);

    //        this.Property(c => c.GRPUSER_ID)
    //            .HasColumnName("GRPUSER_ID")
    //            .IsRequired();

    //        this.Property(c => c.GRU_ID)
    //            .HasColumnName("GRU_ID")
    //            .IsRequired();

    //        this.HasRequired(c => c.T_Grupo)
    //            .WithMany(c => c.T_USER_GRUPO)
    //            .HasForeignKey(c => c.GRU_ID);

    //        this.Property(c => c.ID_USUARIO)
    //            .HasColumnName("ID_USUARIO")
    //            .IsRequired();

    //        this.HasRequired(c => c.T_Usuario)
    //            .WithMany(c => c.T_USER_GRUPO)
    //            .HasForeignKey(c => c.ID_USUARIO);

    //        // Configurando a Tabela
    //        this.ToTable("T_USER_GRUPO");
    //    }
    //    */

    //    public void Configure(EntityTypeBuilder<T_USER_GRUPO> builder)
    //    {
    //        // Configurando propriedades e chaves
    //        builder.HasKey(c => new { c.GRU_ID, c.ID_USUARIO });

    //        builder.Property(c => c.GRU_ID)
    //            .HasColumnName("GRU_ID")
    //            .IsRequired();

    //        builder.HasOne(c => c.T_Grupo)
    //            .WithMany(c => c.T_USER_GRUPO)
    //            .HasForeignKey(c => c.GRU_ID);

    //        builder.Property(c => c.ID_USUARIO)
    //            .HasColumnName("USE_ID")
    //            .IsRequired();

    //        builder.HasOne(c => c.T_Usuario)
    //            .WithMany(c => c.T_USER_GRUPO)
    //            .HasForeignKey(c => c.ID_USUARIO);

    //        // Configurando a Tabela
    //        builder.ToTable("T_USER_GRUPO");
    //    }

    //}
}
