//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicForms.Areas.SGI.Model
{
    using DynamicForms.Areas.SGI.Model;
    using DynamicForms.Models;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Metadata.Builders;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class vw_SGI_PARAMETRO_RELMEDICOES
    {
        [TAB(Value = "PRINCIPAL")] [Display(Name = "DATA_MEDICAO")] [MaxLength(8, ErrorMessage = "Maximode 8 caracteres, campo MED_DATA_MEDICAO")] public string MED_DATA_MEDICAO { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "DATA")] public DateTime MED_DATA { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "ID")] public int? MET_ID { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "ID")] [Required(ErrorMessage = "Campo NEG_ID requirido.")] public int NEG_ID { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "ID")] [Required(ErrorMessage = "Campo IND_ID requirido.")] public int IND_ID { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "")] public int? UNID { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "")] [MaxLength(20, ErrorMessage = "Maximode 20 caracteres, campo UN")] public string UN { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "DESCRICAO")] [Required(ErrorMessage = "Campo IND_DESCRICAO requirido.")] [MaxLength(200, ErrorMessage = "Maximode 200 caracteres, campo IND_DESCRICAO")] public string IND_DESCRICAO { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "")] [MaxLength(6, ErrorMessage = "Maximode 6 caracteres, campo Mes")] public string Mes { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "r")] public double? Valor { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "")] public double? META { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "rAc")] [Required(ErrorMessage = "Campo ValorAc requirido.")] public double ValorAc { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "MES")] public double? METAMES { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "CU")] public double? METACU { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "PONDERACAO")] [Required(ErrorMessage = "Campo MED_PONDERACAO requirido.")] public double MED_PONDERACAO { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "d")] [MaxLength(200, ErrorMessage = "Maximode 200 caracteres, campo DimId")] public string DimId { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "escricao")] [MaxLength(200, ErrorMessage = "Maximode 200 caracteres, campo DimDescricao")] public string DimDescricao { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "d")] [MaxLength(200, ErrorMessage = "Maximode 200 caracteres, campo FatId")] public string FatId { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "escricao")] [MaxLength(200, ErrorMessage = "Maximode 200 caracteres, campo FatDescricao")] public string FatDescricao { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "d")] [MaxLength(3, ErrorMessage = "Maximode 3 caracteres, campo PerId")] public string PerId { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "escricao")] [MaxLength(30, ErrorMessage = "Maximode 30 caracteres, campo PerDescricao")] public string PerDescricao { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "d")] [Required(ErrorMessage = "Campo MedId requirido.")] public int MedId { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "ubId")] [MaxLength(200, ErrorMessage = "Maximode 200 caracteres, campo DimSubId")] public string DimSubId { get; set; }
        [TAB(Value = "PRINCIPAL")] [Display(Name = "ubDescricao")] [MaxLength(200, ErrorMessage = "Maximode 200 caracteres, campo DimSubDescricao")] public string DimSubDescricao { get; set; }
        [NotMapped] public string PlayAction { get; set; }
        [NotMapped] public string PlayMsgErroValidacao { get; set; }
        [NotMapped] public int? IndexClone { get; set; }
        //public bool BeforeChanges(List<object> objects, ref CloneObjeto cloneObjeto, List<LogPlay> Logs, ref int modo_insert) {  } 

        [NotMapped]
        public virtual ICollection<Dimensao>Dimensoes { get; set; }
    }
    
}
